const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('shell', {
  i18n: ipcRenderer.sendSync('shell:i18n'),
  downloadsPick: () => ipcRenderer.invoke('shell:downloads-pick'),
  downloadsOpen: () => ipcRenderer.send('shell:downloads-open'),
  onState: (cb) => ipcRenderer.on('shell:state', (_e, state) => cb(state)),
  onModal: (cb) => ipcRenderer.on('shell:modal', (_e, name, data) => cb(name, data)),
  activate: (id) => ipcRenderer.send('shell:activate', id),
  openSection: (index) => ipcRenderer.send('shell:section', index),
  waAction: (action) => ipcRenderer.send('shell:wa-action', action),
  openModal: (name) => ipcRenderer.send('shell:modal', name),
  closeModal: () => ipcRenderer.send('shell:close-modal'),
  lock: () => ipcRenderer.send('shell:lock'),
  unlock: (code) => ipcRenderer.invoke('shell:unlock', code),
  setPasscode: (current, next) => ipcRenderer.invoke('shell:set-passcode', current, next),
  setTheme: (theme) => ipcRenderer.send('shell:theme', theme),
  setAutostart: (enabled) => ipcRenderer.send('shell:autostart', enabled),
  setAutoLock: (minutes) => ipcRenderer.send('shell:autolock', minutes),
  addAccount: (name) => ipcRenderer.send('shell:add-account', name),
  renameAccount: (id, name) => ipcRenderer.send('shell:rename-account', id, name),
  removeAccount: (id) => ipcRenderer.send('shell:remove-account', id),
  badge: (dataUrl, count, tray1, tray2) => ipcRenderer.send('shell:badge', dataUrl, count, tray1, tray2),
  trayBase: () => ipcRenderer.invoke('shell:tray-base'),
  setSetting: (key, value) => ipcRenderer.send('shell:setting', key, value),
  setAccountMuted: (id, muted) => ipcRenderer.send('shell:account-muted', id, muted),
  scheduleAdd: (data) => ipcRenderer.invoke('shell:schedule-add', data),
  scheduleCancel: (id) => ipcRenderer.send('shell:schedule-cancel', id),
  editSave: (data) => ipcRenderer.invoke('shell:edit-save', data),
  chatList: () => ipcRenderer.invoke('shell:chat-list'),
  forward: (data) => ipcRenderer.invoke('shell:forward', data),
  reminderAdd: (data) => ipcRenderer.invoke('shell:reminder-add', data),
  reminderCancel: (id) => ipcRenderer.send('shell:reminder-cancel', id),
  folderSave: (folder) => ipcRenderer.invoke('shell:folder-save', folder),
  folderDelete: (id) => ipcRenderer.send('shell:folder-delete', id),
  setLockedChats: (ids) => ipcRenderer.send('shell:locked-chats', ids),
  setTemplates: (list) => ipcRenderer.send('shell:templates', list),
  setAccountSound: (id, sound) => ipcRenderer.send('shell:account-sound', id, sound),
  miniMode: () => ipcRenderer.send('shell:mini-mode'),
  favorite: (action) => ipcRenderer.send('shell:favorite', action),
  testNote: () => ipcRenderer.send('shell:test-note'),
  backupExport: () => ipcRenderer.invoke('shell:backup-export'),
  backupImport: () => ipcRenderer.invoke('shell:backup-import')
});
